version: '3'

services:
  backend:
    restart: unless-stopped
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: development
    volumes:
      - .:/workspace:cached
    ports:
      - "3500:8080"
    tty: true
  frontend:
    restart: unless-stopped
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: development
    volumes:
      # - ./frontend/src:/app/src
      # - ./frontend/static:/app/static
      # - ./frontend/vite.config.ts:/app/vite.config.ts
      # - ./frontend/tsconfig.json:/app/tsconfig.json
      # - ./frontend/svelte.config.js:/app/svelte.config.js
      # - ./frontend/tailwind.config.js:/app/tailwind.config.js
      # - ./frontend/postcss.config.js:/app/postcss.config.js
      - .:/workspace:cached
      - /workspace/frontend/node_modules
    ports:
      - "3501:5173"
    tty: true
    # user: node